namespace KinectToVR
{
	runtimeclass TrackingDevicesView : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		TrackingDevicesView(String DeviceName);

		Int32 DeviceID;
		String DeviceName;
		Boolean Current;
	}
}