namespace Amethyst
{
	runtimeclass CalibrationDeviceEntryView : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		CalibrationDeviceEntryView(
			String DeviceGUID,
			String DisplayName,
			Boolean IsBase,
			Boolean IsOverride,
			Boolean StatusError);

		String DeviceGUID;
		String DisplayName;
		Boolean IsBase;
		Boolean IsOverride;
		Boolean StatusError;

		Double BoolToOpacity(Boolean value);
		Double ErrorToOpacity(Boolean value);
	}
}