namespace Amethyst
{
	runtimeclass TrackingDevicesView : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		TrackingDevicesView(String DeviceName);
		TrackingDevicesView(Int32 DeviceID, String DeviceName, Boolean Current);

		Int32 DeviceID;
		String DeviceName;
		Boolean Current;
	}
}